### ISSUE TITLE
hello,I have this question when I run this code!

### ISSUE THREAD

**Issue by BCWang93** [ShangtongZhang/DistributedES#2]
I get this error when I run this code.Can you help me ?Thanks!
D:\Python\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "e:\VScode project\rl_ga\DistributedES\natural_es.py", line 154, in <module>
    all_tasks()
  File "e:\VScode project\rl_ga\DistributedES\natural_es.py", line 150, in all_tasks
    for p in ps: p.start()
  File "D:\Python\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Python\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Python\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'PendulumConfig.__init__.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "D:\Python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] 鎷掔粷璁块棶銆?

**Comment by ShangtongZhang** [comment]
Sorry I never run this on windows.

**Comment by BCWang93** [comment]
> Sorry I never run this on windows.

Thanks，I also solved this error!On the other hand ,how can I see the Result curve?Thanks!

**Comment by dhineshkumar-r** [comment]
@BCWang93 Can you share how you fixed this pickling error on windows?
Thanks
